FROM php:8.2-apache

# Instalar la extensión mysqli
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Copiar los archivos del proyecto al directorio del servidor
COPY . /var/www/html/

EXPOSE 80